### PR TITLE
Use ulog from libubox

### PR DESCRIPTION
**Pull request by zhaojh329**
Signed-off-by: Jianhui Zhao <jianhuizhao329@gmail.com>

### CODE REVIEW

**Comment by br101** [comment]
Hi and thanks for your contribution! Unfortunatly I can not accept it... I use LOG_INF, LOG_ERR, ... macros in many of my projects and got so used to them that I don't want to change them for one project only. If you want the log to go thru ulog you could change log.c to do that. That would be fine with me, allthough I do not see the big benefit either... What's your reason anyways?

**Comment by zhaojh329** [comment]
OK. When do you update feed for openwrt?

**Comment by br101** [comment]
OK will do now, thanks anyways

**Comment by br101** [comment]
https://github.com/openwrt/packages/pull/5699

**Pull request closed without merging**
